### ISSUE TITLE
When DD: DD_RUM and/or DD_LOGS? (what datadog products are they using?)

### ISSUE THREAD

**Issue by cstavitsky** [sentry-demos/detective-scentry#10]
- Currently we just detect the presence of DD.

**Comment by ndmanvar** [comment]
Datadog Errors is built into RUM (`DD_RUM`)

**Comment by ndmanvar** [comment]
we coudl detect LOGS + RUM.
![image](https://user-images.githubusercontent.com/314061/194393680-5484e631-9e31-4322-aaf5-f88e05640666.png)


Although we're more interested in RUM

**Comment by ndmanvar** [comment]
neil to find url where datadog logs + rum are on.

**Comment by ndmanvar** [comment]
https://docs.datadoghq.com/logs/log_collection/javascript/#npm

**Comment by ndmanvar** [comment]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/314061/204913241-201bc4ba-c807-4ba4-a222-292fa5d5366f.png">

**Comment by cstavitsky** [comment]
Implemented in https://github.com/sentry-demos/detective-scentry/pull/28
