### ISSUE TITLE
Detect current Sentry SDK version being used as well as the latest version

### ISSUE THREAD

**Issue by cstavitsky** [sentry-demos/detective-scentry#11]
- i.e. user may be using a version of the Javascript Sentry SDK that is really old, where performance doesn't even exist as an option
- Also include the latest version of the SDK, so that we know how big the gap is between the latest and what they're on
- credit to Simon for this idea

**Comment by ndmanvar** [comment]
Neil picking this up

**Comment by ndmanvar** [comment]
this might not be straightforward...as its not in the __SENTRY__ object

**Comment by cstavitsky** [comment]
@ndmanvar - 

```
__SENTRY__.hub.getClient().getOptions()._metadata.sdk
```

**Comment by cstavitsky** [comment]
And to get the latest version of the SDK for comparison, I'm assuming we'd probably fetch that from Github releases?

**Comment by ndmanvar** [comment]
yep, likely from GH releases.


Looks like `__SENTRY__.hub.getClient().getOptions()._metadata.sdk` won't work in all cases (see reddit.com)


![image](https://user-images.githubusercontent.com/314061/195201555-cba76f4d-8279-4732-8e24-134b145d951f.png)

**Comment by cstavitsky** [comment]
@ndmanvar you still picking this one up?

**Comment by cstavitsky** [comment]
I believe this was implemented in https://github.com/sentry-demos/detective-scentry/pull/22
