### ISSUE TITLE
Detect FullStory

### ISSUE THREAD

**Issue by ndmanvar** [sentry-demos/detective-scentry#18]

**Comment by cstavitsky** [comment]
Check whether Fullstory is loaded via: https://help.fullstory.com/hc/en-us/articles/360032975813-How-do-I-know-that-FullStory-is-deployed-successfully-#method-1-call-fs-getcurrentsessionurl-in-the-console

<img width="938" alt="Screen Shot 2023-01-06 at 12 56 18 PM" src="https://user-images.githubusercontent.com/12092849/211098555-93a2e2ca-2ae2-4bb8-a03a-98df8e43cedd.png">

**Comment by cstavitsky** [comment]
Detected on https://help.fullstory.com/hc/en-us/articles/360020828533-How-do-I-use-the-FullStory-Console-

<img width="1100" alt="Screen Shot 2023-01-06 at 12 57 04 PM" src="https://user-images.githubusercontent.com/12092849/211098653-8686ccf0-172e-4cd6-8a79-7d2e130eafb7.png">

**Comment by cstavitsky** [comment]
Implemented in https://github.com/sentry-demos/detective-scentry/pull/28
