### ISSUE TITLE
Detect Sessionstack

### ISSUE THREAD

**Issue by ndmanvar** [sentry-demos/detective-scentry#19]

**Comment by cstavitsky** [comment]
Used on sessionstack.com
- `SessionStack`
- and maybe check the `isLoaded` attribute as well as seen in the screenshot

<img width="1012" alt="Screen Shot 2023-01-06 at 12 54 06 PM" src="https://user-images.githubusercontent.com/12092849/211098209-98f2cd01-7aac-41fa-bb9b-fbbaae1d108a.png">

**Comment by cstavitsky** [comment]
Implemented in https://github.com/sentry-demos/detective-scentry/pull/28
