### ISSUE TITLE
Sniffing site with Sentry-JS-SDK-v8 causes error

### ISSUE THREAD

**Issue by ndmanvar** [sentry-demos/detective-scentry#45]
https://demo.sentry.io/issues/?project=5808623&query=Cannot+read+properties+of+undefined+%28reading+%27getClient%27%29&referrer=issue-list&statsPeriod=14d
<img width="756" alt="image" src="https://github.com/user-attachments/assets/33ecaa97-205a-4e04-8e6b-e39cfe04c7fe">

**Comment by cstavitsky** [comment]
Fixed in https://github.com/sentry-demos/detective-scentry/pull/51
